TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 2 
  min_in_place_vel_theta: 1.2 
  acc_lim_theta: 3 
  acc_lim_x: 0.75
  acc_lim_y: 0.75
  meter_scoring: true
  holonomic_robot: false
  recovery_behavior_enabled: true
  path_distance_scale: 1.0
  goal_distance_scale: 2.0 
  yaw_goal_tolerance: 5.0 
  xy_goal_tolerance: 0.7
  occdist_scale: 1.0
  clearing_rotation_allowed: false
