autonomous_wheelchair:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_left_holder_to_wheel
    pid: { p: 1.0, i: 0.1, d: 10.0}

  right_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_right_holder_to_wheel
    pid: { p: 1.0, i: 0.1, d: 10.0}