map_type: costmap
obstacle_range: 2.0 
raytrace_range: 2.0 
footprint: [[0.95, -0.32],[0.95, 0.32], [-0.1, 0.32], [-0.1, -0.32]]
transform_tolerance: 1 
inflation_radius: 1.0 
cost_scaling_factor: 5.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
